name: python_template
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pytest
  - flake8
  - black
  - sphinx
  - ipykernel
  - ipywidgets=7.7.1
  - tqdm
  - matplotlib
  - numpy
  - pip:
